app/models/Catalog.php
<?php
/**
 * Created by PhpStorm.
 * User: b059a
 * Date: 10.03.2017
 * Time: 23:11
 */

namespace app\models;


use yii\base\Object;

class Catalog extends Object
{
    /**
     * Название
     * @var string
     */
    public $title;
    /**
     * Категория
     * @var \yii\easyii\modules\catalog\api\CategoryObject
     */
    public $cat;

    /**
     * Товары
     * @var \yii\easyii\modules\catalog\api\ItemObject[]
     */
    public $items;
}

app/controllers/CatalogController.php
<?php

namespace app\controllers;

use Yii;
use yii\easyii\modules\catalog\api\Catalog;
use \app\models\Catalog as Ctlg;
use yii\easyii\modules\entity\api\Entity;
use yii\easyii\modules\page\api\Page;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\NotFoundHttpException;

class CatalogController extends \yii\web\Controller
{
    /**
     * Список категорий
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionIndex()
    {
        /*
        $filterForm = new \app\models\FilterForm();
        $filters = [];
        if($filterForm->load(Yii::$app->request->get()) && $filterForm->validate()) {
            $filters = $filterForm->parse();
        }

        $catalog = [];

        //Клей
        $cat = Catalog::cat('klei');
        $properties = $cat->fieldOptions('properties');
        $filterForm->setPropertiesOptions($properties);
        $filterForm->setColorOptions($cat->fieldOptions('color'));
        $filterForm->setPackageOptions($cat->fieldOptions('package'));
        foreach ($properties as $property){
            if (isset($filters['properties']) && !in_array($property, $filters['properties'])){
                continue;
            }
            $itemsFilters = $filters;
            $itemsFilters['properties'] = $property;
            $catalog[] = new Ctlg([
                'title' => 'Клей '.$property,
                'cat' => $cat,
                'items' => $cat->getItems([
                    'filters' => $itemsFilters,
                ])
            ]);
        }
        //Сырье для клея
        $cat = Catalog::cat('syre-dlya-kleya');
        $properties = $cat->fieldOptions('properties');
        $filterForm->setPropertiesOptions($properties);
        $filterForm->setColorOptions($cat->fieldOptions('color'));
        $filterForm->setPackageOptions($cat->fieldOptions('package'));
        foreach ($properties as $property){
            if (isset($filters['properties']) && !in_array($property, $filters['properties'])){
                continue;
            }
            $itemsFilters = $filters;
            $itemsFilters['properties'] = $property;
            $catalog[] = new Ctlg([
                'title' => $property,
                'cat' => $cat,
                'items' => $cat->getItems([
                    'filters' => $itemsFilters,
                ])
            ]);
        }

        //Оборудование
        $cat = Catalog::cat('oborudovanie');
        $properties = $cat->fieldOptions('properties');
        $filterForm->setPropertiesOptions($properties);
        foreach ($properties as $property){
            if (isset($filters['properties']) && !in_array($property, $filters['properties'])){
                continue;
            }
            $itemsFilters = $filters;
            $itemsFilters['properties'] = $property;
            $catalog[] = new Ctlg([
                'title' => $property,
                'cat' => $cat,
                'items' => $cat->getItems([
                    'filters' => $itemsFilters,
                ])
            ]);
        }

        //Фурнитура
        $cat = Catalog::cat('furnitura');
        $properties = $cat->fieldOptions('properties');
        $filterForm->setPropertiesOptions($properties);
        foreach ($properties as $property){
            if (isset($filters['properties']) && !in_array($property, $filters['properties'])){
                continue;
            }
            $itemsFilters = $filters;
            $itemsFilters['properties'] = $property;
            $catalog[] = new Ctlg([
                'title' => $property,
                'cat' => $cat,
                'items' => $cat->getItems([
                    'filters' => $itemsFilters,
                ])
            ]);
        }


        */
        $catalogs = Catalog::cats();
        /*foreach($catalogs as $ctlg){
            //echo '<strong>' . $ctlg->title . '</strong><br/>';
            //echo $ctlg->description . '<br/><br/>';
            //print_r(get_object_vars($ctlg));
            //print_r(get_class_methods($ctlg));break;
        }*/
        $page = Page::get('catalog');
        if(!$page){
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('index',[
            'catalogs'=>$catalogs,
            'page'=>$page,
            //'catalog'=>$catalog,
            //'filterForm'=>$filterForm,
        ]);
    }

    /**
     * Список товаров в категории
     * @param string $slug Категория
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionCat($slug)
    {
        $catalog = [];
        $cat = Catalog::cat($slug);
        if(!$cat){
            throw new NotFoundHttpException('Category not found.');
        }
        $properties = $cat->fieldOptions('properties');
        foreach ($properties as $property){
            $catalog[] = new Ctlg([
                'title' => $property,
                'cat' => $cat,
                'items' => $cat->getItems([
                    'pagination' => false,
                    'filters' => [
                        'properties' => $property,
                    ],
                ])
            ]);
        }
        return $this->render('cat', [
            'cat' => $cat,
            'catalog'=>$catalog,
        ]);
    }

    /*protected function getFilterForm($slug){
        switch ($slug){
            case 'syre-dlya-kleya':
                return new \app\models\SyryeFilterForm();
            case 'klei':
                return new \app\models\KleyFilterForm();
            default:
                throw new NotFoundHttpException('Category not found.'); 
        }
    }*/

    /*public function actionSearch($text)
    {
        $text = filter_var($text, FILTER_SANITIZE_STRING);

        return $this->render('search', [
            'text' => $text,
            'items' => Catalog::items([
                'where' => ['or', ['like', 'title', $text], ['like', 'description', $text]],
            ])
        ]);
    }*/

    /**
     * Просмотр полной информации о товаре
     * @param string $category Категория
     * @param string $slug Товар
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($category, $slug)
    {
        $cat = Catalog::cat($category);
        if(!$cat){
            throw new NotFoundHttpException('Category not found.');
        }
        $item = Catalog::get($slug);
        if(!$item){
            throw new NotFoundHttpException('Item not found.');
        }
        
        $address = Entity::cat('address');

        /*$filterForm = new \app\models\FilterForm();
        $filterForm->setAllOptions();*/

        return $this->render($category.'/view', [
            'item' => $item,
            'cat' => $cat,
            'address'=>$address,
//            'filterForm' => $filterForm
//            'addToCartForm' => new \app\models\AddToCartForm()
        ]);
    }
}

app/views/catalog/syre-dlya-kleya/_filter.php
<?php
/** @var  $items \yii\easyii\modules\catalog\api\ItemObject[] */
/** @var  $cat \yii\easyii\modules\catalog\api\CategoryObject */
/** @var  $filterForm \app\models\SyryeFilterForm */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>

<p>Выберите параметры</p>
<div class="well well-sm filter_syre">
<?php $form = ActiveForm::begin(['method' => 'get', 'action' => Url::to(['/catalog/cat', 'slug' => $cat->slug])]); ?>
<?= $form->field($filterForm, 'type')->dropDownList($cat->fieldOptions('type', 'Не выбрано'),['onchange'=>'this.form.submit()']) ?>
<?php ActiveForm::end(); ?>
</div>

app/views/catalog/syre-dlya-kleya/_item.php
<?php
/** @var $item \yii\easyii\modules\catalog\api\ItemObject */

/** @var $cat \yii\easyii\modules\catalog\api\CategoryObject */

use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="catalog_item">
    <div class="col catalog_image">
        <a href="<?= Url::to(['catalog/view', 'category' => $item->cat->slug, 'slug' => $item->slug]) ?>">
            <?= Html::img($item->thumb(95, 95), ['class' => 'img-responsive']) ?>
        </a>
    </div>
    <div class="col catalog_desc">
        <h3>
            <?= Html::a($item->title, ['catalog/view', 'category' => $item->cat->slug, 'slug' => $item->slug]) ?>
        </h3>
        <p>
            <?php if (!empty($item->data->color)) : ?>
                <span class="text-muted">Цвет:</span> <?= implode(', ', $item->data->color) ?>
            <?php endif; ?>
        </p>
        <p>
            <?php if (!empty($item->data->package)) : ?>
                <span class="text-muted">Упаковка:</span> <?= implode(', ', $item->data->package) ?>
            <?php endif; ?>
        </p>
    </div>
    <div class="col catalog_price">
        <div class="price">
            <?php if (!empty($item->getPrice())): ?>
                от <?= $item->getPrice() ?> руб.
            <?php else: ?>
                цена по запросу
            <?php endif; ?>
        </div>
        <?= Html::a('Подробнее', ['catalog/view', 'category' => $item->cat->slug, 'slug' => $item->slug], ['class' => 'btn']) ?>
    </div>
</div>

app/views/catalog/syre-dlya-kleya/_item_carousel.php
<?php
/** @var $item \yii\easyii\modules\catalog\api\ItemObject */
/** @var $cat \yii\easyii\modules\catalog\api\CategoryObject */
use app\helpers\Html;
use yii\helpers\Url;

?>
<div class="col-item">
    <div class="info col-md-10 col-md-offset-2 col-xs-12">
        <a href="<?= Url::to(['catalog/view', 'category' => $cat->slug, 'slug' => $item->slug]) ?>">
            <?= Html::img($item->thumb(350, 380)) ?>
        </a>
        <div class="row">
            <div class="col-md-6 col-xs-12">
                <a href="<?= Url::to(['catalog/view', 'category' => $cat->slug, 'slug' => $item->slug]) ?>">
                    <h3 class="clearfix"><?= $item->title ?>
                        <span class="price">
                        <?php if (!empty($item->getPrice())): ?>
                            от <?=$item->getPrice()?> руб.
                        <?php else:?>
                            цена по запросу
                        <?php endif;?>
                        </span>
                    </h3>
                    <p>
                        <?= $item->shortdescription ?>
                    </p>
                </a>
                <div class="controls">
                    <a href="<?= \yii\helpers\Url::to(['/catalog']) ?>" class="btn btn-catalog">Каталог
                        сырья</a>
                    <a class="left btn" href="#syrie-carousel"
                       data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
                    <a class="right btn"
                       href="#syrie-carousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
                </div>
            </div>
        </div>
        <div class="clearfix">
        </div>
    </div>
</div>

app/views/catalog/syre-dlya-kleya/_view_description.php
<?php

/** @var $item \yii\easyii\modules\catalog\api\ItemObject */
use yii\easyii\modules\feedback\api\Feedback;

?>

    <p>
        <?php if (!empty($item->data->color)) : ?>
            <span class="text-muted">Цвет:</span> <?= implode(', ', $item->data->color) ?>
        <?php endif; ?>
    </p>
    <p>
        <?php if (!empty($item->data->package)) : ?>
            <span class="text-muted">Фасовка:</span> <?= implode(', ', $item->data->package) ?>
        <?php endif; ?>
    </p>
<?php /*
    <p>
        <span class="text-muted">Вид сырья:</span>
        <ul>
            <?php foreach ($item->data->properties as $properties): ?>
                <li><?= $properties ?></li>
            <?php endforeach; ?>
        </ul>
    </p> */ ?>
<?= $item->description ?>

app/views/catalog/syre-dlya-kleya/view.php
<?php
/** @var $item \yii\easyii\modules\catalog\api\ItemObject */
/** @var  $cat \yii\easyii\modules\catalog\api\CategoryObject */
/** @var $address \yii\easyii\modules\entity\api\CategoryObject */

use yii\bootstrap\Tabs;
use yii\easyii\modules\catalog\api\Catalog;
use yii\helpers\Html;
$this->registerMetaTag([
    'name' => 'description',
    'content' => $item->seo('description')
]);
$this->title = $item->seo('title', $item->model->title);
$this->params['breadcrumbs'][] = ['label' => 'Shop', 'url' => ['shop/index']];
$this->params['breadcrumbs'][] = ['label' => $item->cat->title, 'url' => ['shop/cat', 'slug' => $item->cat->slug]];
$this->params['breadcrumbs'][] = $item->model->title;
?>

<section class="page">
    <div class="container">
        <div class="col-md-3">
            <?php /* <div class="pr_card_menu col-md-12 col-sm-6">
                <?=$this->render('//catalog/_filter',['cat'=>$cat, 'filterForm' => $filterForm]);?>
            </div> */ ?>
            <?=$this->render('//catalog/_cat_info');?>
        </div>
        <div class="col-md-9">
            <div class="header col-md-12 col-sm-12">
                <h1><?= $item->seo('h1', $item->title) ?></h1>
            </div>
            <div class="product col-md-12">
                <div class="row">
                    <div class="col-md-5">
                        <?= Html::img($item->thumb(350),['class'=>'img-responsive']) ?>
                        <?php if(count($item->photos)) : ?>
                            <br/><br/>
                            <div>
                                <?php foreach($item->photos as $photo) : ?>
                                    <?= $photo->box(null, 100) ?>
                                <?php endforeach;?>
                                <?php Catalog::plugin() ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="col-md-7">
                        <div class="col-lg-12">
                            <h3 class="clearfix">
                                <?php if (!empty($item->getPrice())): ?>
                                    от <?=$item->getPrice()?> руб.
                                <?php else:?>
                                    цена по запросу
                                <?php endif;?>
                            </h3>
                            <p><span class="blue">В наличии</span></p>
                            <button class="btn" data-toggle="modal" data-target="#order-modal" onclick="metrikaReachGoal('callback-modal')">Оформить <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"> </button>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <p class="head">Доставка - 1 день</p>
                            <div class="col-md-1 col-xs-1">
                                <span class="glyphicon glyphicon-road" aria-hidden="true"></span>
                            </div>
                            <div class="col-md-11">
                                <p class="desc">
                                    Доставка до ТК или склада в Москве и МО бесплатная, остальные регионы - нужно уточнять
                                </p>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <p class="head">Самовывоз - сегодня</p>
                            <div class="col-md-1 col-xs-1"><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span></div>
                            <div class="col-md-11">
                                <p class="desc"><?= $address->getItems()[0]->{'address-production'} ?></p></div>
                        </div>
                    </div>
                </div>
                <div class="clearfix">
                </div>
            </div>
            <div class="product_details">
                <?= Tabs::widget([
                    'items' => [
                        [
                            'label' => 'Описание',
                            'content' => $this->render('_view_description', ['item' => $item]),
                            'active' => true
                        ],
                    ]
                ]); ?>

                <?php if (isset($item->data->extra)):?>
                    <?=$item->data->extra?>
                <?php endif; ?>
            </div><!--/container-->
</section>