app/controllers/ArticlesController.php
<?php

namespace app\controllers;

use yii\easyii\models\Tag;
use yii\easyii\modules\article\api\Article;

class ArticlesController extends \yii\web\Controller
{
    /*public function actionIndex()
    {
        return $this->render('index');
    }*/

    public function actionCat($slug, $tag = null)
    {
        $cat = Article::cat($slug);
        if (!$cat) {
            throw new \yii\web\NotFoundHttpException('Article category not found.');
        }
        $tags = Tag::find()->orderBy('frequency DESC')->limit(10)->asArray()->all();

        return $this->render('cat', [
            'cat' => $cat,
            'items' => $cat->getItems(['tags' => $tag, 'pagination' => ['pageSize' => 4]]),
            'tags' => $tags,
        ]);
    }

    public function actionView($category,$slug)
    {
        $cat = Article::cat($category);
        if(!$cat){
            throw new \yii\web\NotFoundHttpException('Article category not found.');
        }
        $article = Article::get($slug);
        if(!$article){
            throw new \yii\web\NotFoundHttpException('Article not found.');
        }

        return $this->render('view', [
            'article' => $article
        ]);
    }

}

app/views/articles/_item.php
<?php
/** @var $item \yii\easyii\modules\article\api\ArticleObject */
/** @var $cat \yii\easyii\modules\article\api\CategoryObject */
use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="blog-block col-md-6 col-sm-12 col-xs-12">
    <a href="<?= \yii\helpers\Url::to(['articles/view', 'category' => $cat->slug, 'slug' => $item->slug]) ?>">
        <div class="text-center">
            <?= Html::img($item->thumb(340, 260)) ?>
        </div>
        <p class="date"><?= \Yii::$app->formatter->asDate($item->time, 'long') ?></p>
        <h3><?= $item->title ?></h3>
        <p class="desc"><?= $item->short ?></p>
    </a>
    <p class="tags">
        <?php foreach ($item->tags as $tag) : ?>
            <a href="<?= Url::to(['/articles/cat', 'slug' => $item->cat->slug, 'tag' => $tag]) ?>"
               class="label label-info"><?= $tag ?></a>
        <?php endforeach; ?>
    </p>
    <p class="blog_btn"><?= Html::a('Подробнее', ['articles/view', 'category' => $cat->slug, 'slug' => $item->slug], ['class' => 'btn']) ?></p>
</div>

app/views/articles/_tags.php
<?php
/** @var $tags array */
/** @var $cat \yii\easyii\modules\article\api\CategoryObject */

use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="category-article">
    <?php foreach($tags as $tag) : ?>
    <a href="<?= Url::to(['/articles/cat', 'slug' => $cat->slug, 'tag' => $tag['name']]) ?>">
        <h3><?= $tag['name'] ?> <span><?= $tag['frequency'] ?></span></h3>
    </a>
    <?php endforeach; ?>
</div>

app/views/articles/cat.php
<?php
/** @var $cat \yii\easyii\modules\article\api\CategoryObject */
/** @var $items \yii\easyii\modules\article\api\ArticleObject[] */
/** @var $tags \yii\easyii\models\Tag[] */

use yii\easyii\modules\article\api\Article;

/** @var $tags array */

$this->registerMetaTag([
    'name' => 'description',
    'content' => $cat->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $cat->seo('keywords')
]);
$this->title = $cat->seo('title', $cat->title);
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['articles/index']];
$this->params['breadcrumbs'][] = $cat->title;
?>

<section class="page blog">
    <div class="container">
        <div class="header col-md-12 col-sm-12 col-xs-12">
            <h1><?= $cat->seo('h1', $cat->title) ?></h1>
        </div>
        <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
        <?php
        foreach($items as $article) {
            echo $this->render('//articles/_item', ['item' => $article, 'cat' => $cat]);
        }
        ?>
        <!-- Пагинация-->
        <?= $cat->getPages()?>
        <!-- / Пагинация-->
        </div>
    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 col-xs-12">
        <div class="category-articles col-md-12 col-sm-6 col-xs-12">
            <h2>Категории:</h2>
            <div class="category-article">
                <?=$this->render('//articles/_tags', ['tags' => $tags, 'cat' => $cat]);?>
            </div>
        </div>
    </div>
    </div><!--/container-->
</section>

app/views/articles/view.php
<?php
/** @var $article \yii\easyii\modules\article\api\ArticleObject */

use yii\easyii\modules\article\api\Article;
use yii\helpers\Html;
use yii\helpers\Url;

$this->registerMetaTag([
    'name' => 'description',
    'content' => $article->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $article->seo('keywords')
]);
$this->title = $article->seo('title', $article->title);
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['articles/index']];
$this->params['breadcrumbs'][] = ['label' => $article->cat->title, 'url' => ['articles/cat', 'slug' => $article->cat->slug]];
$this->params['breadcrumbs'][] = $article->title;
?>

<section class="page">
    <div class="container">
        <div class="header col-md-12 col-sm-12">
            <h1><?= $article->seo('h1', $article->title) ?></h1>
        </div>
        <div class="blog-img col-md-12">
            <?= Html::img($article->thumb(340, 260)) ?>
        </div>
        <div class="blog-page">
            <div>
            <?php if(count($article->text)) : ?>
                        <?= $article->text ?>
            <?php endif; ?>
            </div>
            <div>
            <?php if(count($article->photos)) : ?>
                <div>
                    <h4>Фото</h4>
                    <?php foreach($article->photos as $photo) : ?>
                        <?= $photo->box(100, 100) ?>
                    <?php endforeach;?>
                    <?php Article::plugin() ?>
                </div>
                <br/>
            <?php endif; ?>
            </div>
            <p>
                <?php foreach($article->tags as $tag) : ?>
                    <a href="<?= Url::to(['/articles/cat', 'slug' => $article->cat->slug, 'tag' => $tag]) ?>" class="label label-info"><?= $tag ?></a>
                <?php endforeach; ?>
            </p>

            <p><small class="text-muted"><strong>Дата публикации:</strong> <?=\Yii::$app->formatter->asDate($article->time,'long')?></small></p>
            <p><small class="text-muted"><strong>Просмотры:</strong> <?= $article->views?></small></p>
        </div>
    </div><!--/container-->
</section>