app/models/Catalog.php
<?php
/**
 * Created by PhpStorm.
 * User: b059a
 * Date: 10.03.2017
 * Time: 23:11
 */

namespace app\models;


use yii\base\Object;

class Catalog extends Object
{
    /**
     * Название
     * @var string
     */
    public $title;
    /**
     * Категория
     * @var \yii\easyii\modules\catalog\api\CategoryObject
     */
    public $cat;

    /**
     * Товары
     * @var \yii\easyii\modules\catalog\api\ItemObject[]
     */
    public $items;
}

app/controllers/CatalogController.php
<?php

namespace app\controllers;

use Yii;
use yii\easyii\modules\catalog\api\Catalog;
use \app\models\Catalog as Ctlg;
use yii\easyii\modules\entity\api\Entity;
use yii\easyii\modules\page\api\Page;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\NotFoundHttpException;

class CatalogController extends \yii\web\Controller
{
    /**
     * Список категорий
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionIndex()
    {
        /*
        $filterForm = new \app\models\FilterForm();
        $filters = [];
        if($filterForm->load(Yii::$app->request->get()) && $filterForm->validate()) {
            $filters = $filterForm->parse();
        }

        $catalog = [];

        //Клей
        $cat = Catalog::cat('klei');
        $properties = $cat->fieldOptions('properties');
        $filterForm->setPropertiesOptions($properties);
        $filterForm->setColorOptions($cat->fieldOptions('color'));
        $filterForm->setPackageOptions($cat->fieldOptions('package'));
        foreach ($properties as $property){
            if (isset($filters['properties']) && !in_array($property, $filters['properties'])){
                continue;
            }
            $itemsFilters = $filters;
            $itemsFilters['properties'] = $property;
            $catalog[] = new Ctlg([
                'title' => 'Клей '.$property,
                'cat' => $cat,
                'items' => $cat->getItems([
                    'filters' => $itemsFilters,
                ])
            ]);
        }
        //Сырье для клея
        $cat = Catalog::cat('syre-dlya-kleya');
        $properties = $cat->fieldOptions('properties');
        $filterForm->setPropertiesOptions($properties);
        $filterForm->setColorOptions($cat->fieldOptions('color'));
        $filterForm->setPackageOptions($cat->fieldOptions('package'));
        foreach ($properties as $property){
            if (isset($filters['properties']) && !in_array($property, $filters['properties'])){
                continue;
            }
            $itemsFilters = $filters;
            $itemsFilters['properties'] = $property;
            $catalog[] = new Ctlg([
                'title' => $property,
                'cat' => $cat,
                'items' => $cat->getItems([
                    'filters' => $itemsFilters,
                ])
            ]);
        }

        //Оборудование
        $cat = Catalog::cat('oborudovanie');
        $properties = $cat->fieldOptions('properties');
        $filterForm->setPropertiesOptions($properties);
        foreach ($properties as $property){
            if (isset($filters['properties']) && !in_array($property, $filters['properties'])){
                continue;
            }
            $itemsFilters = $filters;
            $itemsFilters['properties'] = $property;
            $catalog[] = new Ctlg([
                'title' => $property,
                'cat' => $cat,
                'items' => $cat->getItems([
                    'filters' => $itemsFilters,
                ])
            ]);
        }

        //Фурнитура
        $cat = Catalog::cat('furnitura');
        $properties = $cat->fieldOptions('properties');
        $filterForm->setPropertiesOptions($properties);
        foreach ($properties as $property){
            if (isset($filters['properties']) && !in_array($property, $filters['properties'])){
                continue;
            }
            $itemsFilters = $filters;
            $itemsFilters['properties'] = $property;
            $catalog[] = new Ctlg([
                'title' => $property,
                'cat' => $cat,
                'items' => $cat->getItems([
                    'filters' => $itemsFilters,
                ])
            ]);
        }


        */
        $catalogs = Catalog::cats();
        /*foreach($catalogs as $ctlg){
            //echo '<strong>' . $ctlg->title . '</strong><br/>';
            //echo $ctlg->description . '<br/><br/>';
            //print_r(get_object_vars($ctlg));
            //print_r(get_class_methods($ctlg));break;
        }*/
        $page = Page::get('catalog');
        if(!$page){
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('index',[
            'catalogs'=>$catalogs,
            'page'=>$page,
            //'catalog'=>$catalog,
            //'filterForm'=>$filterForm,
        ]);
    }

    /**
     * Список товаров в категории
     * @param string $slug Категория
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionCat($slug)
    {
        $catalog = [];
        $cat = Catalog::cat($slug);
        if(!$cat){
            throw new NotFoundHttpException('Category not found.');
        }
        $properties = $cat->fieldOptions('properties');
        foreach ($properties as $property){
            $catalog[] = new Ctlg([
                'title' => $property,
                'cat' => $cat,
                'items' => $cat->getItems([
                    'pagination' => false,
                    'filters' => [
                        'properties' => $property,
                    ],
                ])
            ]);
        }
        return $this->render('cat', [
            'cat' => $cat,
            'catalog'=>$catalog,
        ]);
    }

    /*protected function getFilterForm($slug){
        switch ($slug){
            case 'syre-dlya-kleya':
                return new \app\models\SyryeFilterForm();
            case 'klei':
                return new \app\models\KleyFilterForm();
            default:
                throw new NotFoundHttpException('Category not found.'); 
        }
    }*/

    /*public function actionSearch($text)
    {
        $text = filter_var($text, FILTER_SANITIZE_STRING);

        return $this->render('search', [
            'text' => $text,
            'items' => Catalog::items([
                'where' => ['or', ['like', 'title', $text], ['like', 'description', $text]],
            ])
        ]);
    }*/

    /**
     * Просмотр полной информации о товаре
     * @param string $category Категория
     * @param string $slug Товар
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($category, $slug)
    {
        $cat = Catalog::cat($category);
        if(!$cat){
            throw new NotFoundHttpException('Category not found.');
        }
        $item = Catalog::get($slug);
        if(!$item){
            throw new NotFoundHttpException('Item not found.');
        }
        
        $address = Entity::cat('address');

        /*$filterForm = new \app\models\FilterForm();
        $filterForm->setAllOptions();*/

        return $this->render($category.'/view', [
            'item' => $item,
            'cat' => $cat,
            'address'=>$address,
//            'filterForm' => $filterForm
//            'addToCartForm' => new \app\models\AddToCartForm()
        ]);
    }
}

app/views/catalog/_cat_info.php
<?php
/** @var $this \yii\web\View */
use app\helpers\Html;
use yii\easyii\helpers\Image;
use yii\helpers\Url;
?>

<div class="pr_card_menu col-md-12 col-sm-6 hidden-xs">
    <p>Сертификат соответствия</p>
    <p>
        <a href="<?=Url::to('/uploads/catalog/cert.pdf')?>" target="_blank">
            <?php
            $thumb = Image::thumb('/uploads/catalog/cert.png', 200, null);
            $thumb = '/uploads/catalog/cert.png';
            echo Html::img($thumb, ['class'=>'img-responsive']);//center-block
            ?>
        </a>
    </p>
</div>
<div class="pr_card_menu col-md-12 hidden-sm hidden-xs">
    <p>Не хотите долго искать?</p>
    <button class="btn" data-toggle="modal" data-target=".callback-modal" onclick="metrikaReachGoal('callback-modal')">Свяжитесь с нами</button>
</div>

app/views/catalog/_filter.php
<?php
/** @var  $items \yii\easyii\modules\catalog\api\ItemObject[] */
/** @var  $filterForm \app\models\FilterForm */

use app\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
?>

<p>Выберите параметры</p>
<div class="well well-sm">
<?php $form = ActiveForm::begin([
        'method' => 'get',
        'action' => Url::to(['/catalog/index']),
        'options'=>[
            'class' => 'filter-form',
        ]
]); ?>
<?php /*= $form->field($filterForm, 'properties')->dropDownList($filterForm->getPropertiesOptions(),['onchange'=>'this.form.submit()'])*/ ?>
<?php /*foreach ($filterForm->getPropertiesOptions('') as $value => $label): ?>
    <?=$form->field($filterForm, 'properties[]')->checkbox([
            'value' => $value,
            'label' => Html::ucfirst($label),
    ]); ?>
<?php endforeach;*/ ?>
<?= $form->field($filterForm, 'properties')->checkboxList($filterForm->getPropertiesOptions(''),['itemOptions'=>['onclick'=>'this.form.submit()']]) ?>

<?= $form->field($filterForm, 'color')->dropDownList($filterForm->getColorOptions(),['onchange'=>'this.form.submit()']) ?>
<?= $form->field($filterForm, 'package')->dropDownList($filterForm->getPackageOptions(),['onchange'=>'this.form.submit()']) ?>
<?php ActiveForm::end(); ?>
</div>

app/views/catalog/_order_modal.php
<?php
/** @var $this \yii\web\View */
?>
<div id="order-modal" class="modal fade order-modal" tabindex="-1" role="dialog" aria-labelledby="orderModal" aria-hidden="true">
    <div class="modal-dialog modal-lg flex">
        <div class="modal-content callback">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <div class="callback-h"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> Оформить заказ</div>
            <hr>
            <p>Наши специалисты оперативно свяжутся с Вами для подтверждения заказа, проконсультируют по видам и характеристикам продукции,
                а также помогут подобрать товар.</p>
            <?= \app\widgets\CallbackForm::widget(['button'=>'Оформить заказ']) ?>
        </div>
    </div>
</div>

app/views/catalog/cat.php
<?php
/** @var  $cat \yii\easyii\modules\catalog\api\CategoryObject */

use app\helpers\Html;

/** @var  $catalog \app\models\Catalog[] */


$this->title = $cat->seo('title', $cat->model->title);
$this->params['breadcrumbs'][] = ['label' => 'Shop', 'url' => ['shop/index']];
$this->params['breadcrumbs'][] = $cat->model->title;
$catalogCount = count($catalog);
?>
<section class="page">
    <div class="container">
        <div class="col-md-9 col-md-push-3 col-sm-12">
            <div class="header">
                <h1><?= $cat->seo('h1', $cat->title) ?></h1>
            </div>
            <?php foreach ($catalog as $ctlg): ?>
                <?php if (count($ctlg->items)) : ?>
                    <div class="catalog">
                        <?php if ($catalogCount > 1) : ?>
                            <!-- Подкатегории -->
                            <div class="header">
                                <h2><?= Html::ucfirst($ctlg->title) ?></h2>
                            </div>
                        <?php endif; ?>
                        <?php foreach ($ctlg->items as $item) : ?>
                            <?= $this->render($cat->slug . '/_item', ['item' => $item]); ?>
                        <?php endforeach; ?>
                    </div>
                <?php else : ?>
                    <p>Category is empty</p>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
        <div class="col-md-3 col-md-pull-9 col-sm-12">
            <?= $this->render('//catalog/_cat_info'); ?>
        </div>
    </div><!--/container-->
</section>

app/views/catalog/index.php
<?php
/** @var  $catalog \app\models\Catalog[] */
/** @var $page \yii\easyii\modules\page\api\PageObject */
/** @var  $filterForm \app\models\FilterForm */

/** @var  $catalogs \yii\easyii\modules\catalog\api\CategoryObject[] */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->registerMetaTag([
    'name' => 'description',
    'content' => $page->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $page->seo('keywords')
]);
$this->title = $page->seo('title', $page->title);
$this->params['breadcrumbs'][] = $page->title;
?>
<section class="page">
    <div class="container">
        <?php /*
        <div class="col-md-3 col-sm-12">
            <div class="pr_card_menu col-md-12 col-sm-6">
                <?= $this->render('_filter', ['filterForm' => $filterForm]); ?>
            </div>
            <?= $this->render('//catalog/_cat_info'); ?>
        </div>

        <div class="catalog col-md-9 col-sm-12">
            <?php foreach ($catalog as $ctlg): ?>
                <?php if (count($ctlg->items)) : ?>
                    <div class="row">
                        <div class="header col-md-12 col-sm-12">
                            <h2><?= $ctlg->cat->seo('h1', $ctlg->title) ?></h2>
                                <br/>
                                <?php foreach ($ctlg->items as $item) : ?>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        <div class="catalog_block">
                                            <?= $this->render($ctlg->cat->slug.'/_item', ['item' => $item, 'cat' => $ctlg->cat]) ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            <div class="pagination">
                                <?= $ctlg->cat->getPages() ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>

        */ ?>
        <div class="header col-md-12 col-sm-12 col-xs-12">
            <h1><?= $page->seo('h1', 'Каталог') ?></h1>
        </div>
        <div class="catalog col-md-12 col-sm-12 col-xs-12">
            <div class="row">
                <?php foreach ($catalogs as $ctlg): ?>

                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <div class="catalog_block">
                            <a href="<?= Url::to(['catalog/cat', 'slug' => $ctlg->slug]) ?>">
                                <div class="row">
                                    <div class="col-md-12">
                                        <?= Html::img($ctlg->thumb(160, 160), ['class' => 'img-responsive']); ?>
                                    </div>
                                    <div class="col-md-12 klei_info">
                                        <div class="klei_name">
                                            <p><?= $ctlg->title; ?></p>
                                        </div>
                                        <div class="klei_desc">
                                            <?= $ctlg->description; ?>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <hr>
                                        <?= Html::a('Каталог', ['catalog/cat', 'slug' => $ctlg->slug], ['class' => 'btn']) ?>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <?php
            /*echo '<pre>';
            foreach ($catalogs as $ctlg){
                echo '<strong>' . $ctlg->title . '</strong><br/>';
                echo $ctlg->description . '<br/><br/>';
            }
            echo '</pre>';*/
            ?>
        </div>
    </div><!--/container-->
</section>